name: Frontend Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Node.js 18 설치
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 의존성 설치
        run: npm install

      - name: react-scripts 실행 권한 부여
        run: chmod +x ./node_modules/.bin/react-scripts

      - name: 프론트엔드 빌드
        run: npm run build